[package]
name = "nostr_sdk"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
anyhow = "1.0"
flutter_rust_bridge = "=2.0.0"
nostr-sdk  = { git = "https://github.com/rust-nostr/nostr", rev = "45f8ebf4da89dc8db5a8aea4610476e70bdb540f", default-features = false, features = ["all-nips", "tor"] }

[build-dependencies]
flutter_rust_bridge_codegen = "=2.0.0"
